"""
Console-Based WORDLE Game
Author: Molly O'Connor
Description: A text-based Wordle game in Python. Players have 6 attempts to guess a secret 5-letter word.
Feedback is provided with colored letters and symbols:
    Green (✓) = correct letter, correct position
    Yellow (~) = correct letter, wrong position
    Red (x) = letter not in the word
"""

import random
from collections import Counter


def read_word_file(filename):
    """
    Reads a text file and returns a list of words. Expected that each word is on its own line.
    """
    word_list = []
    try:
        with open(filename) as filename:
            for line in filename:
                line = line.strip()
                word_list.append(line)
    except FileNotFoundError:
        print("File not found")
    return word_list


def word_getter(list_of_words):
    """
    Randomly selects and returns a word from a list of words.
    """
    secret_word = random.choice(list_of_words)
    return secret_word


def ready_to_play():
    """
    Prompts the player to start the game.
    Accepts 'y' or 'n' as input and validates it.
    """
    valid_input = False
    while not valid_input:
        ready = input("Ready to play? (y/n): ").lower()
        if ready == 'y':
            valid_input = True
            print("Great! Let's start the game!")
            game_loop()
        elif ready == 'n':
            print("LAME, maybe next time! Bye")
            valid_input = True
        else:
            print("Please type 'y' or 'n'. ")


def start_game():
    """
    Displays the welcome message and game instructions,
    then prompts the player to start the game.
    """

    # Instructions generated by chatgpt
    print("Welcome to WORDLE!")
    print("""
    Objective: Guess the secret 5-letter word in 6 tries.

    How to Play:
    1. Type a 5-letter word as your guess.
    2. You will get feedback for each letter, with colors:
       \033[92m✓\033[0m = correct letter in the correct spot (green)
       \033[93m~\033[0m = correct letter in the wrong spot (yellow)
       \033[90mx\033[0m = letter not in the word (grey)
    3. The feedback symbols appear below the letters to help you track your guesses.
    4. Use the colors and symbols to refine your next guess.
    5. Keep guessing until you find the word or run out of tries.

    Good luck!
    """)

    ready_to_play()


def check_letters(secret_word, guess):
    """
    Compares the guessed word to the secret word.
    Prints colored feedback for each letter:
        Green (✓) = correct position
        Yellow (~) = wrong position
        Red (x) = not in word
    Correctly handles repeated letters in the guess.
    """
    guess_letters = list(guess)
    secret_letters = list(secret_word)

    # Tracks how many of each letter are in the secret word
    # Method found on GeeksforGeeks
    secret_count = Counter(secret_letters)

    top_row = ""
    bottom_row = [""] * 5  # Allows me to assign by index, which strings cannot do (used later with .join)

    # Mark exact matches (green)
    for i in range(5):
        if guess_letters[i] == secret_letters[i]:
            # Colors generated by chatgpt
            top_row += f"\033[1;92m{guess_letters[i].upper()}\033[0m "  # Green
            bottom_row[i] = f"\033[1;92m✓\033[0m"
            secret_count[guess_letters[i]] -= 1
        else:
            top_row += f"{guess_letters[i]} "  # Placeholder, will color in second pass

    # Mark letters in the word but wrong spot (yellow) or not in word (grey)
    for i in range(5):
        if bottom_row[i] == "":
            # Only mark as yellow (~) if the letter exists in the word and hasn’t been used yet
            # Example: secret_word = "FLAME", guess = "AALII" (should only mark one A as (~))
            if guess_letters[i] in secret_count and secret_count[guess_letters[i]] > 0:
                # Letter exists but wrong spot
                color = "\033[1;93m"  # yellow
                bottom_row[i] = f"{color}~\033[0m"
                top_row = top_row.split()
                top_row[i] = f"{color}{guess_letters[i].upper()}\033[0m"
                top_row = " ".join(top_row)
                secret_count[guess_letters[i]] -= 1
            else:
                # Letter not in word
                color = "\033[1;90m"  # grey
                bottom_row[i] = f"{color}x\033[0m"
                top_row = top_row.split()
                top_row[i] = f"{color}{guess_letters[i].upper()}\033[0m"
                top_row = " ".join(top_row)

    print(top_row)
    # Matches the top row string to the bottom row characters
    print(" ".join(bottom_row))


def valid_guess(word_list):
    """
    Prompts the player for a valid 5-letter guess.
    Ensures input is in the large word list, has 5 letters, only contains letters,
    and hasn’t been guessed already.
    """
    words_guessed = []
    valid_guess = False
    while not valid_guess:
        guess = input("Please enter a 5 letter word, or type 'xxxxx' to quit: ").lower()
        if len(guess) != 5:
            print("Please type a 5-letter word as your guess.")
        elif guess == "xxxxx":
            valid_guess = True
        elif not guess.isalpha():
            # Checks to make sure the word has all valid characters
            print("Please only type letters (no numbers or symbols).")
        elif guess not in word_list:
            print("That’s not a valid word in our dictionary, please try again.")
        elif guess in words_guessed:
            print("You already guessed that word, please try a new one.")
        else:
            valid_guess = True
            words_guessed.append(guess)

    return guess


def play_again():
    """
    Asks the player if they want to play again after finishing a game.
    """
    again = input("Do you want to play again? (y/n): ").lower()
    if again == 'y':
        print("Great! Here we go again!")
        game_loop()
    elif again == 'n':
        print("Thanks for playing! See ya!")
    else:
        print("Please type 'y' or 'n'. ")


def game_loop():
    """
    Main game loop.
    Picks a secret word, checks guesses, provides feedback,
    and stops if the player wins or runs out of attempts.
    """
    # Made from list of more common words, used to pick the secret word
    secret_word = word_getter(read_word_file("words.txt"))
    print(secret_word)

    # Made from a larger set of all five-letter words, this is used to check if they entered a valid word
    word_list = read_word_file("complex_words.txt")
    word_list2 = read_word_file("words.txt")
    # Merge the word lists and remove duplicates to create a master list of valid guesses
    combined_words = list(set(word_list + word_list2))

    attempts = 6
    while attempts > 0:
        guess = valid_guess(combined_words)
        attempts -= 1
        check_letters(secret_word, guess)
        if guess == secret_word:
            print(f"🎉 Congratulations! You guessed the word: {secret_word}")
            play_again()
            break
        if guess == 'xxxxx':
            print("Thanks for playing!")
            break
        print(f"You have {attempts} attempts left.")
    if guess != secret_word and guess != 'xxxxx' and guess != 'secret_word':
        print(f"😢 Sorry, you didn't guess the word: {secret_word}")
        play_again()


if __name__ == '__main__':
    start_game()
